GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmaXNuaWtAZXhhbXBsZS5jb20iLCJuYmYiOjE2NjEwMzk4ODksInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJtbi1qZGJjLWF1dGgiLCJsYW5ndWFnZSI6InNxIiwiZXhwIjoxNjYxMDQzNDg5LCJpYXQiOjE2NjEwMzk4ODksImhhaXJfY29sb3IiOiJicm93biJ9.CfLnKDjxJNkKuifEpypM5HF3vlKjmtAS9SF_Szfe-2Q